# TCL File Generated by Component Editor 21.1
# Tue Apr 25 19:09:45 EDT 2023
# DO NOT MODIFY


# 
# iir_detector "IIR Detector" v1.0
#  2023.04.25.19:09:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module iir_detector
# 
set_module_property DESCRIPTION ""
set_module_property NAME iir_detector
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "IIR Detector"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_assignment embeddedsw.dts.vendor "csee4840"
set_module_assignment embeddedsw.dts.name "detector"
set_module_assignment embeddedsw.dts.group "detector"

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL detector
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file detector.sv SYSTEM_VERILOG PATH detector.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter ARR_WIDTH INTEGER 16
set_parameter_property ARR_WIDTH DEFAULT_VALUE 16
set_parameter_property ARR_WIDTH DISPLAY_NAME ARR_WIDTH
set_parameter_property ARR_WIDTH TYPE INTEGER
set_parameter_property ARR_WIDTH UNITS None
set_parameter_property ARR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ARR_WIDTH HDL_PARAMETER true


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.group iir_detector
set_module_assignment embeddedsw.dts.name iir_detector
set_module_assignment embeddedsw.dts.vendor csee4840


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point detector
# 
add_interface detector conduit end
set_interface_property detector associatedClock clock
set_interface_property detector associatedReset ""
set_interface_property detector ENABLED true
set_interface_property detector EXPORT_OF ""
set_interface_property detector PORT_NAME_MAP ""
set_interface_property detector CMSIS_SVD_VARIABLES ""
set_interface_property detector SVD_ADDRESS_GROUP ""

add_interface_port detector result result Output 3
add_interface_port detector overall_result overall_result Output 3
add_interface_port detector flag flag Output 1


# 
# connection point power_1
# 
add_interface power_1 conduit end
set_interface_property power_1 associatedClock clock
set_interface_property power_1 associatedReset ""
set_interface_property power_1 ENABLED true
set_interface_property power_1 EXPORT_OF ""
set_interface_property power_1 PORT_NAME_MAP ""
set_interface_property power_1 CMSIS_SVD_VARIABLES ""
set_interface_property power_1 SVD_ADDRESS_GROUP ""

add_interface_port power_1 power_1 power Input 64
add_interface_port power_1 advance1 done Input 1


# 
# connection point power_2
# 
add_interface power_2 conduit end
set_interface_property power_2 associatedClock clock
set_interface_property power_2 associatedReset ""
set_interface_property power_2 ENABLED true
set_interface_property power_2 EXPORT_OF ""
set_interface_property power_2 PORT_NAME_MAP ""
set_interface_property power_2 CMSIS_SVD_VARIABLES ""
set_interface_property power_2 SVD_ADDRESS_GROUP ""

add_interface_port power_2 power_2 power Input 64
add_interface_port power_2 advance2 done Input 1


# 
# connection point power_3
# 
add_interface power_3 conduit end
set_interface_property power_3 associatedClock clock
set_interface_property power_3 associatedReset ""
set_interface_property power_3 ENABLED true
set_interface_property power_3 EXPORT_OF ""
set_interface_property power_3 PORT_NAME_MAP ""
set_interface_property power_3 CMSIS_SVD_VARIABLES ""
set_interface_property power_3 SVD_ADDRESS_GROUP ""

add_interface_port power_3 power_3 power Input 64
add_interface_port power_3 advance3 done Input 1


# 
# connection point power_4
# 
add_interface power_4 conduit end
set_interface_property power_4 associatedClock clock
set_interface_property power_4 associatedReset ""
set_interface_property power_4 ENABLED true
set_interface_property power_4 EXPORT_OF ""
set_interface_property power_4 PORT_NAME_MAP ""
set_interface_property power_4 CMSIS_SVD_VARIABLES ""
set_interface_property power_4 SVD_ADDRESS_GROUP ""

add_interface_port power_4 power_4 power Input 64
add_interface_port power_4 advance4 done Input 1

