# TCL File Generated by Component Editor 21.1
# Fri Apr 28 19:04:40 EDT 2023
# DO NOT MODIFY


# 
# sprites "sprites" v1.0
#  2023.04.28.19:04:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sprites
# 
set_module_property DESCRIPTION ""
set_module_property NAME sprites
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME sprites
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sprites
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sprites.sv SYSTEM_VERILOG PATH sprites.sv TOP_LEVEL_FILE
add_fileset_file 0.mem OTHER PATH sprites/Sprite_rom/0.mem
add_fileset_file 1.txt OTHER PATH sprites/Sprite_rom/1.txt
add_fileset_file 2.txt OTHER PATH sprites/Sprite_rom/2.txt
add_fileset_file 3.txt OTHER PATH sprites/Sprite_rom/3.txt
add_fileset_file 4.txt OTHER PATH sprites/Sprite_rom/4.txt
add_fileset_file 5.txt OTHER PATH sprites/Sprite_rom/5.txt
add_fileset_file 6.txt OTHER PATH sprites/Sprite_rom/6.txt
add_fileset_file 7.txt OTHER PATH sprites/Sprite_rom/7.txt
add_fileset_file 8.txt OTHER PATH sprites/Sprite_rom/8.txt
add_fileset_file 9.txt OTHER PATH sprites/Sprite_rom/9.txt
add_fileset_file B.txt OTHER PATH sprites/Sprite_rom/B.txt
add_fileset_file Blue-left.txt OTHER PATH sprites/Sprite_rom/Blue-left.txt
add_fileset_file Blue-right.txt OTHER PATH sprites/Sprite_rom/Blue-right.txt
add_fileset_file C.txt OTHER PATH sprites/Sprite_rom/C.txt
add_fileset_file E.txt OTHER PATH sprites/Sprite_rom/E.txt
add_fileset_file M.txt OTHER PATH sprites/Sprite_rom/M.txt
add_fileset_file O.txt OTHER PATH sprites/Sprite_rom/O.txt
add_fileset_file Orange-left.txt OTHER PATH sprites/Sprite_rom/Orange-left.txt
add_fileset_file Orange-right.txt OTHER PATH sprites/Sprite_rom/Orange-right.txt
add_fileset_file Pink-left.txt OTHER PATH sprites/Sprite_rom/Pink-left.txt
add_fileset_file Pink-right.txt OTHER PATH sprites/Sprite_rom/Pink-right.txt
add_fileset_file Purple-left.txt OTHER PATH sprites/Sprite_rom/Purple-left.txt
add_fileset_file Purple-right.txt OTHER PATH sprites/Sprite_rom/Purple-right.txt
add_fileset_file R.txt OTHER PATH sprites/Sprite_rom/R.txt
add_fileset_file S.txt OTHER PATH sprites/Sprite_rom/S.txt
add_fileset_file pixil-frame-0.txt OTHER PATH sprites/Sprite_rom/pixil-frame-0.txt


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point sprites
# 
add_interface sprites conduit end
set_interface_property sprites associatedClock ""
set_interface_property sprites associatedReset ""
set_interface_property sprites ENABLED true
set_interface_property sprites EXPORT_OF ""
set_interface_property sprites PORT_NAME_MAP ""
set_interface_property sprites CMSIS_SVD_VARIABLES ""
set_interface_property sprites SVD_ADDRESS_GROUP ""

add_interface_port sprites n_sprite n_sprite Input 6
add_interface_port sprites line line Input 10
add_interface_port sprites pixel pixel Input 6
add_interface_port sprites color_code color_code Output 4

